/* ═══════════════════════════════════════════════════════
   mag.js — TechCalc Pro MAG / Druckhaltung
═══════════════════════════════════════════════════════ */
'use strict';
window.MAG_STATE = window.MAG_STATE || {};
const MAG_STANDARD_SIZES = [8,12,18,25,35,50,80,100,140,200,250,300,400,500,600,800,1000,1500,2000];
function _mag$(id){return document.getElementById(id)}
function _magNum(id){const raw=_mag$(id)?.value; if(raw==null||String(raw).trim()==='')return NaN; return parseFloat(String(raw).replace(',','.'))}
function _magFmt(v,d=1,u=''){if(v==null||isNaN(v))return '–'; return Number(v).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})+(u?' '+u:'')}
function _magExpansionCoeff(tMin,tMax,medium){const table=[[0,0],[10,0],[20,.002],[30,.004],[40,.008],[50,.012],[60,.017],[70,.023],[80,.029],[90,.036],[100,.043],[110,.052],[120,.062]]; const interp=T=>{if(T<=table[0][0])return table[0][1]; for(let i=1;i<table.length;i++){const [t1,e1]=table[i-1], [t2,e2]=table[i]; if(T<=t2)return e1+(e2-e1)*((T-t1)/(t2-t1))} return table[table.length-1][1]}; let e=Math.max(0,interp(tMax)-interp(tMin)); if(medium==='glycol25')e*=1.08; if(medium==='glycol35')e*=1.14; return e}
function _magRecommendedSize(v){return MAG_STANDARD_SIZES.find(s=>s>=v)||Math.ceil(v/100)*100}
function calcMAG(){const system=_mag$('mag-system')?.value||'heizung', medium=_mag$('mag-medium')?.value||'water', VA=_magNum('mag-volume'), tMin=_magNum('mag-tmin'), tMax=_magNum('mag-tmax'), h=_magNum('mag-height'), pSV=_magNum('mag-sv'), p0Manual=_magNum('mag-p0'), peManual=_magNum('mag-pe'); const hintEl=_mag$('mag-hints'); const set=(id,txt)=>{const el=_mag$(id); if(el)el.textContent=txt}; if([VA,tMin,tMax,h,pSV].some(isNaN)||VA<=0||pSV<=0||tMax<=tMin){['mag-ve','mag-reserve','mag-vn-min','mag-vn-rec','mag-pressures','mag-pe-out'].forEach(id=>set(id,'–')); if(hintEl)hintEl.innerHTML='Anlagenvolumen, Temperaturen, statische Höhe und Sicherheitsventil eingeben.'; return null} const e=_magExpansionCoeff(tMin,tMax,medium), VE=VA*e, reserve=Math.max(3,VA*.005), p0Auto=Math.max(.8,h/10+.3), p0=(!isNaN(p0Manual)&&p0Manual>0)?p0Manual:p0Auto, pFill=p0+.3, peAuto=Math.max(p0+.5,pSV-.5), pe=(!isNaN(peManual)&&peManual>0)?peManual:peAuto, ok=pe>p0+.1, VNmin=ok?(VE+reserve)*((pe+1)/(pe-p0)):NaN, rec=ok?_magRecommendedSize(VNmin):NaN; set('mag-ve',_magFmt(VE,1,'l')); set('mag-reserve',_magFmt(reserve,1,'l')); set('mag-vn-min',_magFmt(VNmin,1,'l')); set('mag-vn-rec',isNaN(rec)?'Druck prüfen':rec+' l'); set('mag-pressures',_magFmt(p0,1,'bar')+' / '+_magFmt(pFill,1,'bar')); set('mag-pe-out',_magFmt(pe,1,'bar')); const warnings=[]; if(!ok)warnings.push('Enddruck muss deutlich über dem Vordruck liegen. Sicherheitsventil / Druckhaltung prüfen.'); if(pe>=pSV)warnings.push('Enddruck liegt am oder über dem Sicherheitsventil-Ansprechdruck. Reserve erhöhen.'); if(system==='solar')warnings.push('Solar-MAG: Stillstandsvolumen und höhere Temperaturbelastung zusätzlich objektspezifisch prüfen.'); if(medium!=='water')warnings.push('Glykolgemisch berücksichtigt über Zuschlagsfaktor. Herstellerdaten bleiben maßgebend.'); warnings.push('Quick-Check zur Vorauslegung. Vollständige Auslegung nach Herstellerangaben, DIN EN 12828 und objektspezifischer Druckhaltung prüfen.'); if(hintEl)hintEl.innerHTML=warnings.map(w=>'• '+w).join('<br>'); const result={system,medium,VA,tMin,tMax,h,pSV,e,VE,reserve,p0,pFill,pe,VNmin,recommended:rec}; window.MAG_STATE.last=result; return result}
function initMAG(){['mag-system','mag-medium','mag-volume','mag-tmin','mag-tmax','mag-height','mag-sv','mag-p0','mag-pe'].forEach(id=>{_mag$(id)?.addEventListener('input',calcMAG); _mag$(id)?.addEventListener('change',calcMAG)}); _mag$('mag-calc-btn')?.addEventListener('click',calcMAG); calcMAG()}
document.addEventListener('DOMContentLoaded',initMAG);
