const CACHE_NAME = 'techcalc-pro-1.6.1';
const CACHE_REVISION = '1.6.1-version-1-6-1-pdf-export-vereinheitlichung';
const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './RELEASE_NOTES.md',
  './css/components-app-status.css',
  './css/components-collections.css',
  './css/components-controls.css',
  './css/components-core.css',
  './css/components-legacy-contracts.css',
  './css/components-polish.css',
  './css/components-save-manager.css',
  './css/components-settings-release.css',
  './css/components-system.css',
  './css/components.css',
  './css/layout-navigation-theme.css',
  './css/layout.css',
  './css/module-accent-tokens.css',
  './css/module-spacing-contract.css',
  './css/modules-base.css',
  './css/modules-hx.css',
  './css/modules-light-overrides.css',
  './css/modules-pipe.css',
  './css/modules-pressure-buffer.css',
  './css/modules-responsive.css',
  './css/modules-unit.css',
  './css/modules-wrg.css',
  './css/modules.css',
  './css/theme-light-contrast.css',
  './css/theme-light-final.css',
  './css/theme-light-guards.css',
  './css/theme-light-rollout.css',
  './css/theme-light-surfaces.css',
  './css/theme-light.css',
  './css/tokens.css',
  './core/app.js',
  './core/appCore.js',
  './core/centralStore.js',
  './core/collectionModel/index.js',
  './core/collectionRenderer.js',
  './core/contracts/index.js',
  './core/contracts/moduleContract.js',
  './core/contracts/moduleDefinition.js',
  './core/contracts/moduleLayoutContract.js',
  './core/contracts/platformPolicy.js',
  './core/data/calculations.js',
  './core/data/catalog.js',
  './core/data/fGasesSystemSnapshot.js',
  './core/data/index.js',
  './core/data/pipes.js',
  './core/data/rainwater.js',
  './core/data/rainwaterDomainTables.js',
  './core/data/rainwaterSurfaceSnapshot.js',
  './core/data/refrigerants.js',
  './core/data/refrigerants/en378-safety-data.js',
  './core/data/refrigerants/gwp.js',
  './core/data/refrigerants/index.js',
  './core/data/refrigerants/refrigerant-label.js',
  './core/data/refrigerants/refrigerant-service.js',
  './core/data/refrigerants/refrigerants.js',
  './core/data/refrigerants/regulations.js',
  './core/data/refrigerants/safety-classes.js',
  './core/data/units.js',
  './core/diagnostics/appHealth.js',
  './core/diagnostics/index.js',
  './core/diagnostics/performanceBudget.js',
  './core/domUpdate.js',
  './core/engineering/hvacAir.js',
  './core/engineering/hvacAirResults.js',
  './core/engineering/index.js',
  './core/events/eventDelegation.js',
  './core/events/eventManager.js',
  './core/events/eventPipeline.js',
  './core/events/index.js',
  './core/focusManager.js',
  './core/formActions.js',
  './core/formSchema.js',
  './core/index.js',
  './core/lineSectionController/index.js',
  './core/logger.js',
  './core/moduleLifecycleAdapter.js',
  './core/moduleRenderer.js',
  './core/moduleRuntime.js',
  './core/mount.js',
  './core/navigation.js',
  './core/numberService.js',
  './core/numbers.js',
  './core/pdf/authorityCharts.js',
  './core/pdf/authorityCorporateBlock.js',
  './core/pdf/authorityCoverPage.js',
  './core/pdf/authorityExecutiveSummary.js',
  './core/pdf/authorityHeaderPolicy.js',
  './core/pdf/authorityHighlightPolicy.js',
  './core/pdf/authorityLargeDocument.js',
  './core/pdf/authorityPagination.js',
  './core/pdf/authorityPdfReport.js',
  './core/pdf/authorityReportPolicy.js',
  './core/pdf/authorityReportScope.js',
  './core/pdf/authorityTableLayout.js',
  './core/pdf/authorityTableOfContents.js',
  './core/pdf/authorityTables.js',
  './core/pdf/en378ReportSections.js',
  './core/pdf/fGasesReportSections.js',
  './core/pdf/floodingReportSections.js',
  './core/pdf/genericReportSections.js',
  './core/pdf/index.js',
  './core/pdf/pdfChartRender.js',
  './core/pdf/pdfDataMapping.js',
  './core/pdf/pdfLayout.js',
  './core/pdf/pdfText.js',
  './core/pdf/rainwaterReportSections.js',
  './core/pdf/reportTheme.js',
  './core/pdf/ventilationReportSections.js',
  './core/pdfExport.js',
  './core/platformModuleRuntime.js',
  './core/preferences.js',
  './core/projectStorage.js',
  './core/projectStorageBase.js',
  './core/registry.js',
  './core/renderCoordinator.js',
  './core/renderScheduler.js',
  './core/renderer.js',
  './core/resultRenderer.js',
  './core/router.js',
  './core/runtime/index.js',
  './core/runtime/platformLifecycle.js',
  './core/runtime/schemaModuleMount.js',
  './core/saveEditModeSync.js',
  './core/savedRecordController.js',
  './core/savedRecordModel/index.js',
  './core/savedRecords.js',
  './core/schemaRenderer.js',
  './core/scrollManager.js',
  './core/state.js',
  './core/state/index.js',
  './core/state/projectModuleStateAdapters.js',
  './core/stateBinding.js',
  './core/storage/index.js',
  './core/storage/savedCalculationController.js',
  './core/storage/unsavedWorkGuard.js',
  './core/styles/index.js',
  './core/typedDtoReportAdapter.js',
  './core/ui/dynamicRenderer.js',
  './core/ui/index.js',
  './core/ui/uiSystem.js',
  './core/ux/feedbackController.js',
  './core/ux/index.js',
  './core/ux/layoutStabilityController.js',
  './core/ux/performanceController.js',
  './core/ux/releaseNotesController.js',
  './core/ux/serviceWorkerController.js',
  './core/ux/settingsController.js',
  './core/ux/themeController.js',
  './core/version.js',
  './modules/buffer-storage/config.js',
  './modules/buffer-storage/controller.js',
  './modules/buffer-storage/index.js',
  './modules/buffer-storage/logic.js',
  './modules/buffer-storage/results.js',
  './modules/buffer-storage/schema.js',
  './modules/buffer-storage/state.js',
  './modules/buffer-storage/view.js',
  './modules/buffer-storage/viewModel.js',
  './modules/drinking-water/config.js',
  './modules/drinking-water/controller.js',
  './modules/drinking-water/dynamicRenderer.js',
  './modules/drinking-water/index.js',
  './modules/drinking-water/logic.js',
  './modules/drinking-water/results.js',
  './modules/drinking-water/schema.js',
  './modules/drinking-water/state.js',
  './modules/drinking-water/view.js',
  './modules/drinking-water/viewModel.js',
  './modules/en-378-safety-check/alternativeRiskMeasures.js',
  './modules/en-378-safety-check/chargeLimitCalculation.js',
  './modules/en-378-safety-check/config.js',
  './modules/en-378-safety-check/displayLabels.js',
  './modules/en-378-safety-check/importController.js',
  './modules/en-378-safety-check/index.js',
  './modules/en-378-safety-check/installationSafetyRequirements.js',
  './modules/en-378-safety-check/logic.js',
  './modules/en-378-safety-check/plannerGuidance.js',
  './modules/en-378-safety-check/refrigerantCoverage.js',
  './modules/en-378-safety-check/reportAdapter.js',
  './modules/en-378-safety-check/results.js',
  './modules/en-378-safety-check/savedRecords.js',
  './modules/en-378-safety-check/schema.js',
  './modules/en-378-safety-check/snapshotImport.js',
  './modules/en-378-safety-check/state.js',
  './modules/en-378-safety-check/stateConsistency.js',
  './modules/f-gases-check/config.js',
  './modules/f-gases-check/index.js',
  './modules/f-gases-check/logic.js',
  './modules/f-gases-check/reportAdapter.js',
  './modules/f-gases-check/results.js',
  './modules/f-gases-check/savedRecords.js',
  './modules/f-gases-check/schema.js',
  './modules/f-gases-check/state.js',
  './modules/f-gases-check/view.js',
  './modules/flooding-verification/calculationAdapter.js',
  './modules/flooding-verification/config.js',
  './modules/flooding-verification/controller.js',
  './modules/flooding-verification/diagnosticModel.js',
  './modules/flooding-verification/dynamicRenderer.js',
  './modules/flooding-verification/index.js',
  './modules/flooding-verification/interpretationModel.js',
  './modules/flooding-verification/logic.js',
  './modules/flooding-verification/plausibilityModel.js',
  './modules/flooding-verification/reportAdapter.js',
  './modules/flooding-verification/results.js',
  './modules/flooding-verification/retentionApplicability.js',
  './modules/flooding-verification/retentionDurationComparison.js',
  './modules/flooding-verification/retentionFactors.js',
  './modules/flooding-verification/savedRecords.js',
  './modules/flooding-verification/schema.js',
  './modules/flooding-verification/state.js',
  './modules/flooding-verification/view.js',
  './modules/heat-recovery/config.js',
  './modules/heat-recovery/controller.js',
  './modules/heat-recovery/dynamicRenderer.js',
  './modules/heat-recovery/index.js',
  './modules/heat-recovery/logic.js',
  './modules/heat-recovery/results.js',
  './modules/heat-recovery/schema.js',
  './modules/heat-recovery/state.js',
  './modules/heat-recovery/view.js',
  './modules/heat-recovery/viewModel.js',
  './modules/heating-cooling/config.js',
  './modules/heating-cooling/controller.js',
  './modules/heating-cooling/index.js',
  './modules/heating-cooling/logic.js',
  './modules/heating-cooling/reportAdapter.js',
  './modules/heating-cooling/results.js',
  './modules/heating-cooling/schema.js',
  './modules/heating-cooling/state.js',
  './modules/heating-cooling/view.js',
  './modules/heating-cooling/viewModel.js',
  './modules/hx-diagram/config.js',
  './modules/hx-diagram/controller.js',
  './modules/hx-diagram/diagramRenderer.js',
  './modules/hx-diagram/dynamicRenderer.js',
  './modules/hx-diagram/formRenderer.js',
  './modules/hx-diagram/index.js',
  './modules/hx-diagram/logic.js',
  './modules/hx-diagram/renderPipeline.js',
  './modules/hx-diagram/results.js',
  './modules/hx-diagram/schema.js',
  './modules/hx-diagram/state.js',
  './modules/hx-diagram/view.js',
  './modules/hx-diagram/viewModel.js',
  './modules/mixed-air/config.js',
  './modules/mixed-air/controller.js',
  './modules/mixed-air/dynamicRenderer.js',
  './modules/mixed-air/index.js',
  './modules/mixed-air/logic.js',
  './modules/mixed-air/results.js',
  './modules/mixed-air/schema.js',
  './modules/mixed-air/state.js',
  './modules/mixed-air/view.js',
  './modules/mixed-air/viewModel.js',
  './modules/pipe-sizing/config.js',
  './modules/pipe-sizing/controller.js',
  './modules/pipe-sizing/index.js',
  './modules/pipe-sizing/logic.js',
  './modules/pipe-sizing/results.js',
  './modules/pipe-sizing/schema.js',
  './modules/pipe-sizing/state.js',
  './modules/pipe-sizing/view.js',
  './modules/pipe-sizing/viewModel.js',
  './modules/pressure-holding/config.js',
  './modules/pressure-holding/controller.js',
  './modules/pressure-holding/index.js',
  './modules/pressure-holding/logic.js',
  './modules/pressure-holding/results.js',
  './modules/pressure-holding/schema.js',
  './modules/pressure-holding/state.js',
  './modules/pressure-holding/view.js',
  './modules/pressure-holding/viewModel.js',
  './modules/rainwater/config.js',
  './modules/rainwater/controller.js',
  './modules/rainwater/index.js',
  './modules/rainwater/logic.js',
  './modules/rainwater/reportAdapter.js',
  './modules/rainwater/results.js',
  './modules/rainwater/schema.js',
  './modules/rainwater/state.js',
  './modules/rainwater/tables.js',
  './modules/rainwater/view.js',
  './modules/rainwater/viewModel.js',
  './modules/unit-converter/config.js',
  './modules/unit-converter/controller.js',
  './modules/unit-converter/index.js',
  './modules/unit-converter/logic.js',
  './modules/unit-converter/results.js',
  './modules/unit-converter/schema.js',
  './modules/unit-converter/state.js',
  './modules/unit-converter/view.js',
  './modules/unit-converter/viewModel.js',
  './modules/ventilation/config.js',
  './modules/ventilation/controller.js',
  './modules/ventilation/index.js',
  './modules/ventilation/logic.js',
  './modules/ventilation/reportAdapter.js',
  './modules/ventilation/results.js',
  './modules/ventilation/schema.js',
  './modules/ventilation/state.js',
  './modules/ventilation/view.js',
  './modules/ventilation/viewModel.js',
  './modules/wastewater/config.js',
  './modules/wastewater/controller.js',
  './modules/wastewater/index.js',
  './modules/wastewater/logic.js',
  './modules/wastewater/results.js',
  './modules/wastewater/schema.js',
  './modules/wastewater/state.js',
  './modules/wastewater/tables.js',
  './modules/wastewater/view.js',
  './modules/wastewater/viewModel.js',
  './assets/icons/apple-touch-icon.png',
  './assets/icons/favicon.ico',
  './assets/icons/icon-16.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-32.png',
  './assets/icons/icon-512.png',
  './docs/legal/agb.html'
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS)));
});
self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map(key => key === CACHE_NAME ? null : caches.delete(key)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    clients.forEach(client => client.postMessage({ type: 'TECHCALC_CACHE_UPDATED', cache: CACHE_NAME, revision: CACHE_REVISION }));
  })());
});
async function fetchFresh(request) {
  try {
    const response = await fetch(request, { cache: 'no-store' });
    if (response?.ok) {
      const cache = await caches.open(CACHE_NAME);
      await cache.put(request, response.clone());
    }
    return response;
  } catch {
    return null;
  }
}
async function cacheFirstWithRefresh(request) {
  const cached = await caches.match(request);
  if (cached) {
    fetchFresh(request);
    return cached;
  }
  const response = await fetchFresh(request);
  if (response) return response;
  return caches.match('./index.html');
}
function isVersionCriticalAsset(requestUrl) {
  return requestUrl.pathname.endsWith('/index.html')
    || requestUrl.pathname.endsWith('/core/app.js')
    || requestUrl.pathname.endsWith('/core/ux/releaseNotesController.js')
    || requestUrl.pathname.endsWith('/service-worker.js')
    || requestUrl.pathname.endsWith('/RELEASE_NOTES.md')
    || requestUrl.pathname.endsWith('/manifest.json');
}
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  if (event.request.cache === 'only-if-cached' && event.request.mode !== 'same-origin') return;
  const requestUrl = new URL(event.request.url);
  if (requestUrl.origin !== self.location.origin) return;
  const isNavigation = event.request.mode === 'navigate' || event.request.destination === 'document';
  const isReleaseNotes = requestUrl.pathname.endsWith('/RELEASE_NOTES.md') || requestUrl.pathname.endsWith('RELEASE_NOTES.md');
  const isServiceWorker = requestUrl.pathname.endsWith('/service-worker.js') || requestUrl.pathname.endsWith('service-worker.js');
  const isVersionCritical = isVersionCriticalAsset(requestUrl);
  if (isNavigation || isReleaseNotes || isServiceWorker || isVersionCritical) {
    event.respondWith((async () => {
      const fresh = await fetchFresh(event.request);
      if (fresh) return fresh;
      return caches.match(event.request) || caches.match('./index.html');
    })());
    return;
  }
  event.respondWith(cacheFirstWithRefresh(event.request));
});
