import { createModuleState } from '../../core/state.js';

export const FLOODING_VERIFICATION_SCHEMA_VERSION = 2;

export const initialState = {
  schemaVersion: FLOODING_VERIFICATION_SCHEMA_VERSION,
  featureEnabled: true,
  projectName: '',
  surfaceCategory: 'roof',
  surfaceName: '',
  surfaceAreaType: 'metal-roof',
  surfaceArea: '100',
  surfaceCs: '1,0',
  surfaceCm: '0,9',
  rainDurationMode: 'automatic',
  manualRainDuration: '10',
  manualRainDurationReason: '',
  meanSlopePercent: '1,0',
  rainR2Duration5: '',
  rainR2Duration10: '',
  rainR2Duration15: '',
  rainR30Duration5: '',
  rainR30Duration10: '',
  rainR30Duration15: '',
  rainR100Duration5: '',
  rainSourceDataset: '',
  rainSourceLocation: '',
  rainSourceVersion: '',
  rainEntryMode: 'manual',
  dischargeMode: 'table-existing-pipe',
  pipeNominalDiameterDn: 'DN 100',
  pipeSlopePercent: '1,0',
  manualFullFlowLs: '',
  manualFullFlowSource: '',
  authorityLimitLs: '',
  authorityName: '',
  authorityReference: '',
  authorityDate: '',
  authoritySourceNote: '',
  retentionEnabled: false,
  retentionRecurrenceFrequencyPerYear: '',
  retentionFlowTimeMinutes: '',
  retentionRiskClass: 'medium',
  retentionSurchargeFactorFz: '',
  retentionReductionFactorFa: '',
  retentionDryWeatherFlowLs: '0',
  retentionUpstreamThrottleFlowLs: '0',
  retentionRainDuration5: '',
  retentionRainDuration10: '',
  retentionRainDuration15: '',
  retentionRainByDuration: {},
  activeSurfaceId: null,
  expandedSurfaceId: null,
  surfaces: [],
  importedRainwaterSnapshot: null,
  importStatus: '',
  savedVerifications: [],
  activeVerificationId: null,
  expandedVerificationId: null,
  savedVerificationName: '',
  results: null
};

export const state = createModuleState(initialState);
