import { execFileSync } from 'node:child_process';

const commands = [
  ['node', ['scripts/check-js-imports.mjs']],
  ['node', ['tests/number-service.test.mjs']],
  ['node', ['tests/platform-policy.test.mjs']],
  ['node', ['tests/module-contract.test.mjs']],
  ['node', ['tests/saved-record-interaction.test.mjs']],
  ['node', ['tests/input-confirmation.test.mjs']],
  ['node', ['tests/heating-cooling-interaction.test.mjs']],
  ['node', ['tests/heating-cooling-global-standard.test.mjs']],
  ['node', ['tests/heating-cooling-phase12g.test.mjs']],
  ['node', ['tests/heating-cooling-phase12h.test.mjs']],
  ['node', ['tests/heating-cooling-phase12i.test.mjs']],
  ['node', ['tests/ventilation-global-standard.test.mjs']],
  ['node', ['tests/ventilation-phase13e.test.mjs']],
  ['node', ['tests/rainwater-global-standard.test.mjs']],
  ['node', ['tests/rainwater-phase14c.test.mjs']],
  ['node', ['tests/rainwater-phase14d.test.mjs']],
  ['node', ['tests/rainwater-phase14e.test.mjs']],
  ['node', ['tests/rainwater-phase14f.test.mjs']],
  ['node', ['tests/rainwater-phase14g.test.mjs']],
  ['node', ['tests/rainwater-phase14l.test.mjs']],
  ['node', ['tests/router-direct-navigation.test.mjs']],
  ['node', ['tests/router-single-navigation-path.test.mjs']],
  ['node', ['tests/router-same-module-guard-phase15c.test.mjs']],
  ['node', ['tests/dom-cache-loading-regression-phase15e.test.mjs']],
  ['node', ['tests/module-lifecycle-phase15a.test.mjs']],
  ['node', ['tests/module-lifecycle-phase15d.test.mjs']],
  ['node', ['tests/module-runtime-phase16a.test.mjs']],
  ['node', ['tests/saved-record-controller-phase16b.test.mjs']],
  ['node', ['tests/schema-renderer-phase16c.test.mjs']],
  ['node', ['tests/css-system-phase16d.test.mjs']],
  ['node', ['tests/event-pipeline-phase16e.test.mjs']],
  ['node', ['tests/rainwater-phase16e1-recovery.test.mjs']],
  ['node', ['tests/rainwater-phase17a-decoupling.test.mjs']],
  ['node', ['tests/rainwater-phase17a1-decoupling.test.mjs']],
  ['node', ['tests/rainwater-phase17a2-saved-actions.test.mjs']],
  ['node', ['tests/rainwater-phase17a3-results.test.mjs']],
  ['node', ['tests/rainwater-phase17a6-platform-control.test.mjs']],
  ['node', ['tests/wastewater-phase17b-platform-control.test.mjs']],
  ['node', ['tests/wastewater-phase17b1-platform-collections.test.mjs']],
  ['node', ['tests/wastewater-phase17b2-reference-level.test.mjs']],
  ['node', ['tests/reference-modules-phase17c-bugfix.test.mjs']],
  ['node', ['tests/reference-modules-phase17c1-ui-bugfix.test.mjs']],
  ['node', ['tests/reference-modules-phase17c2-reference-fixes.test.mjs']],
  ['node', ['tests/reference-modules-phase17c5-event-scroll.test.mjs']],
  ['node', ['tests/reference-modules-phase17c6-saved-record-root-cause.test.mjs']],
  ['node', ['tests/central-platform-pipeline.test.mjs']],
  ['node', ['tests/state-binding.test.mjs']],
  ['node', ['tests/event-pipeline-phase11d.test.mjs']],
  ['node', ['tests/event-pipeline-rebind.test.mjs']],
  ['node', ['tests/render-coordinator.test.mjs']],
  ['node', ['scripts/audit-module-contracts.mjs']],
  ['node', ['scripts/audit-ui-classes.mjs']],
  ['node', ['scripts/audit-platform-migration.mjs']],
  ['node', ['scripts/audit-css-debt.mjs']],
  ['node', ['scripts/audit-css-system-phase16d.mjs']],
  ['node', ['scripts/audit-important-usage.mjs']],
  ['node', ['scripts/audit-rerender-risk.mjs']],
  ['node', ['scripts/audit-mobile-scroll-stability.mjs']],
  ['node', ['scripts/audit-legacy-event-handlers.mjs']]
];

for (const [cmd, args] of commands) {
  console.log(`> ${cmd} ${args.join(' ')}`);
  execFileSync(cmd, args, { stdio: 'inherit' });
}
console.log('TechCalc quality gate ok');
